[package]
name = "math_optim-rs"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "algebra",
    "dsu", 
    "gf",
]

[dependencies]
algebra = { path = "algebra" }
dsu = { path = "dsu" }
gf = { path = "gf" }
