[package]
name = "math_optim-rs"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "algebra",
    "bitree",
    "dsu", 
    "gf",
    "segtree",
    "rle",
]

[dependencies]
algebra = { path = "algebra" }
bitree = { path = "bitree" }
dsu = { path = "dsu" }
gf = { path = "gf" }
segtree = { path = "segtree" }
rle = { path = "rle" }
